// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/inca-go/node/node.proto

package node

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cid "github.com/aperturerobotics/hydra/cid"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NodeState contains the state of a Node.
type NodeState struct {
	// LastMsgRef is the reference to the last node message.
	LastMsgRef           *cid.BlockRef `protobuf:"bytes,1,opt,name=last_msg_ref,json=lastMsgRef" json:"last_msg_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeState) Reset()         { *m = NodeState{} }
func (m *NodeState) String() string { return proto.CompactTextString(m) }
func (*NodeState) ProtoMessage()    {}
func (*NodeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_6d5e53941ed9b24b, []int{0}
}
func (m *NodeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeState.Unmarshal(m, b)
}
func (m *NodeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeState.Marshal(b, m, deterministic)
}
func (dst *NodeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeState.Merge(dst, src)
}
func (m *NodeState) XXX_Size() int {
	return xxx_messageInfo_NodeState.Size(m)
}
func (m *NodeState) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeState.DiscardUnknown(m)
}

var xxx_messageInfo_NodeState proto.InternalMessageInfo

func (m *NodeState) GetLastMsgRef() *cid.BlockRef {
	if m != nil {
		return m.LastMsgRef
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeState)(nil), "node.NodeState")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/inca-go/node/node.proto", fileDescriptor_node_6d5e53941ed9b24b)
}

var fileDescriptor_node_6d5e53941ed9b24b = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0xcf, 0xcc, 0x4b, 0x4e, 0xd4, 0x4d, 0xcf, 0xd7,
	0xcf, 0xcb, 0x4f, 0x49, 0x05, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6,
	0x94, 0x3e, 0x3e, 0xad, 0x19, 0x95, 0x29, 0x45, 0x89, 0xfa, 0xc9, 0x99, 0x29, 0x20, 0x0c, 0xd1,
	0xa6, 0x64, 0xc3, 0xc5, 0xe9, 0x97, 0x9f, 0x92, 0x1a, 0x5c, 0x92, 0x58, 0x92, 0x2a, 0xa4, 0xcf,
	0xc5, 0x93, 0x93, 0x58, 0x5c, 0x12, 0x9f, 0x5b, 0x9c, 0x1e, 0x5f, 0x94, 0x9a, 0x26, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0xab, 0x07, 0x52, 0xee, 0x94, 0x93, 0x9f, 0x9c, 0x1d, 0x94, 0x9a,
	0x16, 0xc4, 0x05, 0x52, 0xe2, 0x5b, 0x9c, 0x1e, 0x94, 0x9a, 0x96, 0xc4, 0x06, 0x36, 0xc4, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xe8, 0xe5, 0x3b, 0xb2, 0x00, 0x00, 0x00,
}
