// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/inca-go/utils/transaction/txdb/txdb.proto

package txdb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cid "github.com/aperturerobotics/hydra/cid"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TransactionInfo attaches information to a transaction.
type TransactionInfo struct {
	// NodeMessageRef is the reference to the inca.NodeMessage containing the tx.
	NodeMessageRef       *cid.BlockRef `protobuf:"bytes,1,opt,name=node_message_ref,json=nodeMessageRef" json:"node_message_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransactionInfo) Reset()         { *m = TransactionInfo{} }
func (m *TransactionInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionInfo) ProtoMessage()    {}
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdb_6bb1085da3d7f444, []int{0}
}
func (m *TransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInfo.Unmarshal(m, b)
}
func (m *TransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInfo.Marshal(b, m, deterministic)
}
func (dst *TransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInfo.Merge(dst, src)
}
func (m *TransactionInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionInfo.Size(m)
}
func (m *TransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInfo proto.InternalMessageInfo

func (m *TransactionInfo) GetNodeMessageRef() *cid.BlockRef {
	if m != nil {
		return m.NodeMessageRef
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionInfo)(nil), "txdb.TransactionInfo")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/inca-go/utils/transaction/txdb/txdb.proto", fileDescriptor_txdb_6bb1085da3d7f444)
}

var fileDescriptor_txdb_6bb1085da3d7f444 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8c, 0xbd, 0x0b, 0xc2, 0x30,
	0x10, 0x47, 0x29, 0x88, 0x43, 0xc5, 0x0f, 0x3a, 0x89, 0x93, 0x38, 0xb9, 0xd8, 0x80, 0x0e, 0xee,
	0x82, 0x83, 0x82, 0x4b, 0x71, 0x2f, 0xf9, 0xb8, 0xb4, 0xc1, 0x36, 0x57, 0x2e, 0x57, 0xd0, 0xff,
	0x5e, 0xd2, 0x0e, 0x6e, 0x0e, 0x77, 0xfc, 0x86, 0xf7, 0x5e, 0x7a, 0xad, 0x1c, 0xd7, 0xbd, 0xca,
	0x35, 0xb6, 0x42, 0x76, 0x40, 0xdc, 0x13, 0x10, 0x2a, 0x64, 0xa7, 0x83, 0x70, 0x5e, 0xcb, 0x43,
	0x85, 0xa2, 0x67, 0xd7, 0x04, 0xc1, 0x24, 0x7d, 0x90, 0x9a, 0x1d, 0x7a, 0xc1, 0x6f, 0xa3, 0x86,
	0x97, 0x77, 0x84, 0x8c, 0xd9, 0x24, 0xee, 0x8d, 0xf8, 0x17, 0xab, 0x3f, 0x86, 0xa4, 0xd0, 0xce,
	0xc4, 0x1b, 0xb5, 0xdd, 0x3d, 0x5d, 0x3e, 0x7f, 0xd5, 0x9b, 0xb7, 0x98, 0x9d, 0xd3, 0x95, 0x47,
	0x03, 0x65, 0x0b, 0x21, 0xc8, 0x0a, 0x4a, 0x02, 0xbb, 0x4e, 0xb6, 0xc9, 0x7e, 0x76, 0x9c, 0xe7,
	0x51, 0xbc, 0x34, 0xa8, 0x5f, 0x05, 0xd8, 0x62, 0x11, 0xb1, 0xc7, 0x48, 0x15, 0x60, 0xd5, 0x74,
	0x48, 0x9e, 0xbe, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x47, 0x3a, 0x37, 0xd2, 0x00, 0x00, 0x00,
}
