// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/inca-go/examples/chat/chat.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cid "github.com/aperturerobotics/hydra/cid"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ChatState is the application state.
type ChatState struct {
	// MessageCount is the total message count.
	MessageCount uint32 `protobuf:"varint,1,opt,name=message_count,json=messageCount" json:"message_count,omitempty"`
	// LastMessageRef is the latest message reference.
	// Reference type: ChatMessageElem
	LastMessageRef       *cid.BlockRef `protobuf:"bytes,2,opt,name=last_message_ref,json=lastMessageRef" json:"last_message_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChatState) Reset()         { *m = ChatState{} }
func (m *ChatState) String() string { return proto.CompactTextString(m) }
func (*ChatState) ProtoMessage()    {}
func (*ChatState) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_5707c3a58e89d236, []int{0}
}
func (m *ChatState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatState.Unmarshal(m, b)
}
func (m *ChatState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatState.Marshal(b, m, deterministic)
}
func (dst *ChatState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatState.Merge(dst, src)
}
func (m *ChatState) XXX_Size() int {
	return xxx_messageInfo_ChatState.Size(m)
}
func (m *ChatState) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatState.DiscardUnknown(m)
}

var xxx_messageInfo_ChatState proto.InternalMessageInfo

func (m *ChatState) GetMessageCount() uint32 {
	if m != nil {
		return m.MessageCount
	}
	return 0
}

func (m *ChatState) GetLastMessageRef() *cid.BlockRef {
	if m != nil {
		return m.LastMessageRef
	}
	return nil
}

// ChatMessageElem is the chain of chat messages.
type ChatMessageElem struct {
	// ChatMessage is the chat message.
	ChatMessage *ChatMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage" json:"chat_message,omitempty"`
	// Prev is a reference to the previous element.
	Prev                 *cid.BlockRef `protobuf:"bytes,2,opt,name=prev" json:"prev,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChatMessageElem) Reset()         { *m = ChatMessageElem{} }
func (m *ChatMessageElem) String() string { return proto.CompactTextString(m) }
func (*ChatMessageElem) ProtoMessage()    {}
func (*ChatMessageElem) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_5707c3a58e89d236, []int{1}
}
func (m *ChatMessageElem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessageElem.Unmarshal(m, b)
}
func (m *ChatMessageElem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessageElem.Marshal(b, m, deterministic)
}
func (dst *ChatMessageElem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessageElem.Merge(dst, src)
}
func (m *ChatMessageElem) XXX_Size() int {
	return xxx_messageInfo_ChatMessageElem.Size(m)
}
func (m *ChatMessageElem) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessageElem.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessageElem proto.InternalMessageInfo

func (m *ChatMessageElem) GetChatMessage() *ChatMessage {
	if m != nil {
		return m.ChatMessage
	}
	return nil
}

func (m *ChatMessageElem) GetPrev() *cid.BlockRef {
	if m != nil {
		return m.Prev
	}
	return nil
}

// ChatTransaction is a chat transaction.
type ChatTransaction struct {
	// ChatMessage is the chat message.
	ChatMessage          *ChatMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage" json:"chat_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChatTransaction) Reset()         { *m = ChatTransaction{} }
func (m *ChatTransaction) String() string { return proto.CompactTextString(m) }
func (*ChatTransaction) ProtoMessage()    {}
func (*ChatTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_5707c3a58e89d236, []int{2}
}
func (m *ChatTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatTransaction.Unmarshal(m, b)
}
func (m *ChatTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatTransaction.Marshal(b, m, deterministic)
}
func (dst *ChatTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatTransaction.Merge(dst, src)
}
func (m *ChatTransaction) XXX_Size() int {
	return xxx_messageInfo_ChatTransaction.Size(m)
}
func (m *ChatTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ChatTransaction proto.InternalMessageInfo

func (m *ChatTransaction) GetChatMessage() *ChatMessage {
	if m != nil {
		return m.ChatMessage
	}
	return nil
}

// ChatMessage is a chat message.
type ChatMessage struct {
	// SenderName is the sender display name.
	// This is not a secure chat system, just a proof-of-concept.
	SenderName string `protobuf:"bytes,1,opt,name=sender_name,json=senderName" json:"sender_name,omitempty"`
	// MessageText is the sender message text.
	MessageText          string   `protobuf:"bytes,2,opt,name=message_text,json=messageText" json:"message_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_5707c3a58e89d236, []int{3}
}
func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (dst *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(dst, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *ChatMessage) GetMessageText() string {
	if m != nil {
		return m.MessageText
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatState)(nil), "main.ChatState")
	proto.RegisterType((*ChatMessageElem)(nil), "main.ChatMessageElem")
	proto.RegisterType((*ChatTransaction)(nil), "main.ChatTransaction")
	proto.RegisterType((*ChatMessage)(nil), "main.ChatMessage")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/inca-go/examples/chat/chat.proto", fileDescriptor_chat_5707c3a58e89d236)
}

var fileDescriptor_chat_5707c3a58e89d236 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcf, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0xe9, 0x97, 0xf2, 0x85, 0x26, 0xad, 0x3f, 0x72, 0x2a, 0x5e, 0xac, 0xeb, 0xa5, 0x17,
	0x37, 0x50, 0x05, 0x2f, 0x9e, 0x2c, 0xe2, 0x49, 0xc1, 0xd8, 0xfb, 0x32, 0x4d, 0xa7, 0xdd, 0xe8,
	0x26, 0x59, 0x92, 0xa9, 0xd4, 0xff, 0x5e, 0xb2, 0xdb, 0xc5, 0x1e, 0xc4, 0x83, 0x87, 0x04, 0xf2,
	0xe6, 0xe5, 0x7d, 0x66, 0x86, 0xdd, 0x6d, 0x0c, 0x95, 0xdb, 0x65, 0xae, 0xbd, 0x95, 0x50, 0x63,
	0xa0, 0x6d, 0xc0, 0xe0, 0x97, 0x9e, 0x8c, 0x8e, 0xd2, 0x38, 0x0d, 0x57, 0x1b, 0x2f, 0x71, 0x07,
	0xb6, 0xae, 0x30, 0x4a, 0x5d, 0x02, 0x35, 0x57, 0x5e, 0x07, 0x4f, 0x5e, 0xf4, 0x2d, 0x18, 0x77,
	0x26, 0x7f, 0xcb, 0x28, 0x3f, 0x57, 0x01, 0xa4, 0x36, 0xab, 0x74, 0xda, 0x6f, 0x99, 0x61, 0x83,
	0x79, 0x09, 0xf4, 0x4a, 0x40, 0x28, 0x2e, 0xd9, 0xc8, 0x62, 0x8c, 0xb0, 0xc1, 0x42, 0xfb, 0xad,
	0xa3, 0x71, 0x6f, 0xd2, 0x9b, 0x8e, 0xd4, 0x70, 0x2f, 0xce, 0x93, 0x26, 0x6e, 0xd9, 0x49, 0x05,
	0x91, 0x8a, 0xce, 0x19, 0x70, 0x3d, 0xfe, 0x37, 0xe9, 0x4d, 0xf9, 0x6c, 0x94, 0xa7, 0xdc, 0xfb,
	0xca, 0xeb, 0x77, 0x85, 0x6b, 0x75, 0x94, 0x6c, 0x4f, 0xad, 0x4b, 0xe1, 0x3a, 0x7b, 0x63, 0xc7,
	0x09, 0xb5, 0x57, 0x1e, 0x2a, 0xb4, 0xe2, 0x86, 0x0d, 0xd3, 0x08, 0x5d, 0x56, 0xc3, 0xe3, 0xb3,
	0xd3, 0x3c, 0xcd, 0x92, 0x1f, 0x98, 0x15, 0xd7, 0xdf, 0x0f, 0x71, 0xc1, 0xfa, 0x75, 0xc0, 0x8f,
	0x9f, 0xa9, 0x4d, 0x29, 0x7b, 0x6c, 0x59, 0x8b, 0x00, 0x2e, 0x82, 0x26, 0xe3, 0xdd, 0xdf, 0x58,
	0xd9, 0x0b, 0xe3, 0x07, 0x35, 0x71, 0xce, 0x78, 0x44, 0xb7, 0xc2, 0x50, 0x38, 0xb0, 0x6d, 0xc6,
	0x40, 0xb1, 0x56, 0x7a, 0x06, 0x9b, 0x7a, 0xeb, 0xb6, 0x55, 0x10, 0xee, 0xa8, 0xe9, 0x71, 0xa0,
	0xf8, 0x5e, 0x5b, 0xe0, 0x8e, 0x96, 0xff, 0x9b, 0xcd, 0x5f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x2b, 0x7a, 0x2e, 0xe6, 0xf0, 0x01, 0x00, 0x00,
}
